version: '3.8'

services:
  web:
    build: .
    depends_on:
      - elasticsearch
    command: bin/rails server --port 8081 --binding 0.0.0.0
    ports:
      - '8081:8081'
    volumes:
      - .:/usr/src/app

  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9268:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.7
    depends_on:
      - elasticsearch
    ports:
      - 5668:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  es_data:
